In [53]:
import pandas as pd
import pprint

In [45]:
df = pd.read_csv("../Data/premium_houses.csv", sep=';', encoding='ISO-8859-1')

In [46]:
df

,Codigo,Antiguedad,Ascensor,Aseos,Baños,Balcon,Carpinteria Exterior,Carpinteria Interior,Cocina,Distancia a la Playa,...,Solárium,Techos altos,Terraza,Todo exterior,Trastero.1,Tren,Vigilancia 24H,Vistas al mar,Vistas despejadas,Tipo
0,8899299,1972,1,0,1,1,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0,Apartamento
1,8899305,2004,1,0,2,0,NaN,NaN,NaN,0,...,0,0,1,0,1,0,0,0,0,Apartamento
2,16252095,1974,1,0,1,0,Aluminio,Madera,Equipada,0,...,1,0,1,2,1,0,0,0,1,Apartamento
3,8919444,1968,1,0,1,0,NaN,NaN,Equipada,200,...,0,0,0,0,0,0,0,0,0,Apartamento
4,12539901,1962,1,0,1,1,Aluminio,Lacado Blanco,Equipada,50,...,0,0,0,0,0,1,0,0,0,Apartamento
5,9913194,1968,1,0,1,0,NaN,NaN,Equipada,200,...,0,0,0,0,0,1,0,0,0,Apartamento
6,10916993,1966,0,0,1,0,NaN,NaN,Equipada,600,...,0,0,1,0,0,0,0,1,0,Piso
7,17141995,1972,1,0,1,0,Aluminio/Climalit,Madera,NaN,550,...,0,0,1,1,0,1,0,1,1,Apartamento
8,16901484,1997,0,0,5,0,Aluminio,Aluminio,Equipada,1200,...,0,1,0,1,0,0,0,0,1,Casa
9,10805246,1973,0,0,2,0,Aluminio,Aluminio,Equipada,50,...,0,0,1,2,0,0,0,1,1,Apartamento
10,9645673,2004,1,1,2,0,Doble Ventana,NaN,Equipada,500,...,1,0,1,0,1,0,0,1,1,Ático Dúplex
11,9745964,2008,0,1,2,1,NaN,NaN,Equipada,0,...,0,0,1,0,1,0,0,0,1,Casa
12,14990607,2003,1,2,2,0,Aluminio,Aluminio,Solo Muebles,500,...,1,0,1,2,0,0,1,1,1,Dúplex
13,10939655,2014,1,0,2,0,Aluminio/Climalit,Aluminio,Solo Muebles,1000,...,0,0,1,2,1,0,0,0,1,Planta baja
14,9990808,1972,1,0,1,0,NaN,NaN,Equipada,50,...,0,0,1,2,0,0,0,1,1,Apartamento
15,8899377,1997,0,0,2,0,NaN,NaN,NaN,1000,...,0,0,0,0,1,0,0,1,0,Casa
16,12596863,1971,0,0,2,0,Aluminio,Aluminio,Equipada,50,...,0,0,1,2,1,0,0,0,1,Ático Dúplex
17,10191934,1986,0,1,1,0,Aluminio,Madera,Equipada,400,...,0,0,1,0,0,0,0,1,0,Apartamento
18,18336293,1984,0,1,3,0,Aluminio,NaN,Equipada,0,...,0,0,1,1,1,0,0,1,1,Casa
19,9964634,1980,0,0,2,1,Aluminio,NaN,Equipada,270,...,0,0,1,2,0,0,0,0,0,Apartamento
20,8899404,1998,0,0,3,0,NaN,NaN,NaN,0,...,0,0,1,0,0,0,0,0,0,Casa
21,9817292,1996,1,0,2,0,Aluminio/Climalit,NaN,Equipada,1000,...,1,0,1,0,0,1,0,1,1,Apartamento
22,9634174,2008,0,0,3,0,NaN,NaN,Equipada,0,...,0,0,0,0,1,1,0,1,1,Casa
23,10402784,2000,1,1,2,0,NaN,NaN,Equipada,500,...,0,0,1,0,1,1,0,1,1,Ático Dúplex
24,8899302,2007,0,0,2,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0,Casa
25,9661815,2007,0,0,3,1,Aluminio/Climalit,NaN,Equipada,400,...,1,0,1,1,1,1,0,0,0,Casa
26,9956385,1995,0,1,2,0,Aluminio,Madera,Equipada,540,...,0,0,1,0,1,0,0,0,0,Adosado
27,11231987,1990,0,1,3,0,Aluminio,Madera,Equipada,1000,...,0,0,1,1,1,0,0,1,1,Adosado
28,8899322,2002,0,1,3,0,Aluminio/Climalit,Aluminio,Equipada,600,...,1,0,1,2,1,0,0,1,0,Pareado
29,8899364,2000,1,0,3,0,NaN,NaN,NaN,0,...,0,0,1,0,1,0,0,0,0,Dúplex
30,8939205,2000,0,0,3,0,Aluminio/Climalit,NaN,Equipada,200,...,0,0,1,0,0,0,0,0,0,Dúplex
31,15587980,1980,0,1,3,1,Aluminio,NaN,Equipada,2200,...,0,0,1,2,0,0,0,1,1,Casa
32,10202202,2011,1,2,3,0,NaN,NaN,Equipada,1000,...,0,0,1,0,1,0,0,1,0,Casa
33,11225176,1994,1,0,3,0,Aluminio,Madera,Equipada,50,...,0,0,1,2,1,0,0,1,1,Ático Dúplex
34,11457838,2009,0,0,2,0,Aluminio,NaN,Equipada,3000,...,0,0,0,1,0,0,0,1,0,Casa
35,10405501,2004,0,0,3,0,Aluminio/Climalit,NaN,Equipada,100,...,1,0,1,1,1,1,0,0,0,Casa
36,10038916,2008,0,0,5,0,NaN,NaN,Equipada,1200,...,0,0,1,0,1,0,0,0,0,Casa
37,11786420,1991,0,0,4,0,Aluminio-Madera,Aluminio,Solo Muebles,2000,...,1,0,1,2,1,1,0,1,1,Casa
38,10009274,0,1,0,5,1,NaN,NaN,Equipada,500,...,0,0,1,2,1,0,0,1,1,Casa
39,12064887,1992,0,1,3,0,Aluminio,Aluminio,Equipada,0,...,1,0,1,0,1,0,0,0,0,Casa
40,9490869,1967,0,0,4,0,Aluminio-Madera,Madera,Equipada,750,...,0,0,0,2,1,0,0,1,1,Casa
41,10299200,1990,0,1,4,1,Aluminio/Climalit,Aluminio,Equipada,600,...,1,0,1,2,1,0,0,0,1,Casa con terreno
42,13219847,2017,1,1,5,0,NaN,NaN,NaN,1700,...,0,0,1,2,0,0,0,0,1,Casa
43,8899352,0,0,0,5,0,NaN,NaN,NaN,0,...,0,0,1,0,0,0,0,0,0,Casa

In [54]:

print("Columns and Data Types:")
pprint.pprint(df.dtypes)

Columns and Data Types:
Codigo                int64
Antiguedad            int64
Ascensor              int64
Aseos                 int64
Baños                 int64
                      ...
Tren                  int64
Vigilancia 24H        int64
Vistas al mar         int64
Vistas despejadas     int64
Tipo                 object
Length: 108, dtype: object

In [57]:
for column in df.columns:
    print(column)

Codigo
Antiguedad
Ascensor
Aseos
Baños
Balcon
Carpinteria Exterior
Carpinteria Interior
Cocina
Distancia a la Playa
Edificio
Estado Propiedad
Garaje
Hab Doble
Hab Simple
Habitaciones Total
I.B.I.
IBI
M. Altillo
M. Entreplanta
M. Fachada
M. Patio
M. Planta Baja
M. Puerta
M. Sótano
Mt cocina
Mt comedor
Mt Construidos
Mt Parcela
Mt primera plantas
Mt terraza
Mt Utiles
Muebles
N? Parking
N? Plazas Parking
Num Planta
Orientación
Parking
Salón
Tipo calefaccion
Tipo cocina
Tipo Suelo
Trastero
Vistas
Precio Inmobiliaria
Provincia
Ciudad
Zona
Calle Prop
Calle Prop Num
Calle prop Planta
Piso
Aire Acond. Central
Aire Acondicionado
Alarma
Alarma Incendio
Altillo
Apart. Separado
Armarios empotrados
Ascensor.1
Autobuses
Árboles
Balcón
Barbacoa
Bomba frío y calor
Buhardilla
Caja fuerte
Calefacción
Calefacción central
Céntrico
Centros comerciales
Centros médicos
Cerca de Universidad
Chimenea
Colegios
Descalcificador
Despensa
Galería
Garaje.1
Garaje Doble
Gas Ciudad
Gimnasio
Hab. Juegos
Hidromasaje
Jacuzzi
Jardín
Lavandería
Línea telefónica
Luminoso
Luz
Muebles.1
parking
Patio
Piscina Comunitaria
Piscina Propia
Primera Línea
Sauna
Sótano
Solárium
Techos altos
Terraza
Todo exterior
Trastero.1
Tren
Vigilancia 24H
Vistas al mar
Vistas despejadas
Tipo

In [52]:
columns_with_nulls = df.columns[df.isnull().any()]
null_counts = df[columns_with_nulls].isnull().sum().sort_values(ascending=False)

print("Columns with the most null values:")
print(null_counts)

Columns with the most null values:
Edificio                44
Carpinteria Interior    27
Carpinteria Exterior    18
Orientación             17
Vistas                  14
Tipo Suelo              13
Cocina                   9
Zona                     1
dtype: int64

In [ ]:
"""
columns that i will drop = 
Edificio                44
Carpinteria Interior    27
Carpinteria Exterior    18
Orientación             17
Vistas                  14
Tipo Suelo              13

"""

In [61]:
# Assuming 'columns_to_drop' is a list of column names you want to drop
columns_to_drop = ['Edificio', 'Carpinteria Interior', 'Carpinteria Exterior', 'Orientación', 'Vistas', 'Tipo Suelo']

# Drop the specified columns
df.drop(columns=columns_to_drop, inplace=True)

In [62]:
print("\nSummary statistics:")
df.describe()

Summary statistics:

,Codigo,Antiguedad,Ascensor,Aseos,Baños,Balcon,Distancia a la Playa,Hab Doble,Hab Simple,Habitaciones Total,...,Sótano,Solárium,Techos altos,Terraza,Todo exterior,Trastero.1,Tren,Vigilancia 24H,Vistas al mar,Vistas despejadas
count,4.400000e+01,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,...,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000
mean,1.105498e+07,1900.931818,0.409091,0.363636,2.568182,0.181818,544.545455,3.250000,0.477273,3.727273,...,0.159091,0.227273,0.022727,0.772727,0.840909,0.545455,0.204545,0.022727,0.477273,0.500000
std,2.487814e+06,419.890096,0.497350,0.574291,1.227547,0.390154,670.554975,1.630024,1.067242,1.403710,...,0.369989,0.423915,0.150756,0.423915,0.913546,0.503686,0.408032,0.150756,0.505258,0.505781
min,8.899299e+06,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.598348e+06,1972.750000,0.000000,0.000000,2.000000,0.000000,37.500000,2.000000,0.000000,3.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.011542e+07,1994.500000,0.000000,0.000000,2.000000,0.000000,400.000000,3.000000,0.000000,4.000000,...,0.000000,0.000000,0.000000,1.000000,0.500000,1.000000,0.000000,0.000000,0.000000,0.500000
75%,1.153998e+07,2004.000000,1.000000,1.000000,3.000000,0.000000,812.500000,4.250000,0.250000,5.000000,...,0.000000,0.000000,0.000000,1.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,1.833629e+07,2017.000000,1.000000,2.000000,5.000000,1.000000,3000.000000,7.000000,5.000000,7.000000,...,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [63]:
columns_with_nulls = df.columns[df.isnull().any()]
null_counts = df[columns_with_nulls].isnull().sum().sort_values(ascending=False)

print("Columns with the most null values:")
print(null_counts)

Columns with the most null values:
Cocina    9
Zona      1
dtype: int64